-- Add new columns to playbooks table for Etherflow production line
ALTER TABLE public.playbooks 
ADD COLUMN IF NOT EXISTS themes JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS success_patterns_input JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS client_context TEXT,
ADD COLUMN IF NOT EXISTS analysis_id UUID REFERENCES public.content_analyses(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS current_stage TEXT DEFAULT 'analysis',
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending';

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_playbooks_analysis_id ON public.playbooks(analysis_id);
CREATE INDEX IF NOT EXISTS idx_playbooks_user_status ON public.playbooks(user_id, status);

-- Add column to track production stage in contents table
ALTER TABLE public.contents 
ADD COLUMN IF NOT EXISTS production_status TEXT DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS style_checker_details JSONB DEFAULT '{}'::jsonb;

-- Add column to narrative_skeletons for angle variations
ALTER TABLE public.narrative_skeletons 
ADD COLUMN IF NOT EXISTS angle_selected TEXT;

COMMENT ON COLUMN public.playbooks.themes IS 'Array of 10 theme objects generated by ideation agent';
COMMENT ON COLUMN public.playbooks.current_stage IS 'Current stage: analysis, ideation, research, narrative, writing, completed';
COMMENT ON COLUMN public.playbooks.status IS 'Status: pending, in_progress, touchpoint, completed, error';